#+title: Развитие не догмы, но к руководства действию.
#+author: Это я Спартак.





* Главный вопрос.
Начну я пожалуй с банальностей. Всем не раз приходилось слышать фразу "Если вы не занимаетесь политикой, то политика займётся вами". Чуть позже, уже другой человек сказал "Политика — это концентрированное выражение экономики". Сделав некоторое допущение, я думаю, мы можем соединить эти мудрые слова и получить в результате "Если вы не занимаетесь экономикой, то экономика займется(занимается) вами".

Суть существующей системы производства раскрыл Маркс в своем "Капитале", в котором он вскрыл механизм общественно-экономических отношений. Меня интересуют детали развития процессов и способов обмена товарами потому, что при капитализме система производства *фундаментально* зависит от системы обмена. И эти механизмы обмена также претерпевают изменения. А значит все изменения в обменных процессах повлияют на систему производства и их также необходимо рассматривать в развитии. Возможно мне скажут что изменились лишь формы, а не суть этих процессов и явлений. Пусть так. Меня интересует в первую очередь практическая сторона вопроса. 
Поэтому и рассмотрю с точки зрения диамата (если быть честнее, с точки зрения моего понимания диамата) явления не изученные или не существовавшие при жизни Маркса и Ленина. Чисто хохмы ради. Да еще потому, что считаю призывы развивать, пересматривать теорию Маркса, искать новые философские категории в рамках такого его развития преждевременными.

Я буду часто очень категоричен. И, наверняка, абсолютно неправ. Мне позволительно. Все-таки, как-никак, лучший сыщик без диплома. И все же, я прошу прочитать этот результат приступа графомании до конца.

* Мюсли о розничной торговле.

Постараюсь по древу не растекаться. Я вижу три способа:
** древнейший способ торговли (до конца XIX в)

Я думаю, можно сказать, что с самого первого обмена и до появления ценника торговля велась между людьми единственным образом - через умение торговаться между двумя участниками сделки.

** торговля в эпоху становления империализма(как высшей формы капитализма)

В конце девятнадцатого века некий [[https://ru.wikipedia.org/wiki/%D0%92%D1%83%D0%BB%D0%B2%D0%BE%D1%80%D1%82,_%D0%A4%D1%80%D1%8D%D0%BD%D0%BA_%D0%A3%D0%B8%D0%BD%D1%84%D0%B8%D0%BB%D0%B4#:~:text=%D0%A4%D1%80%D1%8D%D0%BD%D0%BA%20%D0%A3%D0%B8%D0%BD%D1%84%D0%B8%D0%BB%D0%B4%20%D0%92%D1%83%D0%BB%D0%B2%D0%BE%D1%80%D1%82%20(%D0%B0%D0%BD%D0%B3%D0%BB.][Фрэнк Уинфилд Вулворт]] придумал ценники, а потом и создал первую сеть магазинов, которые стали прародителями супермаркетов. Изменились отношения между продавцом и покупателем, а также между продавцом и его работодателем (требования к квалификации продавца понижались). Ценники вошли в повседневный обиход и изменили культуру розничной торговли. Самое важное в них - немедленное предоставление информации об установленной цене.

** современная
Современные механизмы стали формироваться в конце девяностых годов прошлого столетия как результат развития торговли по почтовым каталогам. В итоге была сформирована индустрия онлайн-торговли, которая перешла в стадию платформ-агрегаторов, которые сводят вместе тысячи торговых, а нередко и производственных, предприятий и миллионы потребителей. Опять изменились отношения между продавцом и покупателем, фактически удаляя человека-продавца из процесса торговли. Так как процессы укрупнения и монополизации никто не отменял, то, со временем, стоит ожидать слияние предприятий "стоящих за витриной" онлайн-торговли и устранения большей части посредников между платформой и непосредственным производителем.

Развитие, как изменение явления, налицо. Давайте попробуем обнаружить действие законов развития на данном явлении. Возьмем к примеру закон перехода количества в качество.

При торговле на рынке покупатель ограничен в доступе к информации о наличии товаров необходимого качества или товаров способных заместить необходимый где-то в другом месте и, возможно, по другой цене, так же под вопросом находится ценообразование и всегда стоит сначала предложить свою. Сейчас, в обычном розничном магазине, покупатель имеет достаточный доступ к информации о цене, качестве и возможных заменителях в рамках ассортимента торговой точки. И уж нет никаких проблем в получении информации о цене, свойствах и ассортименте предложения с современными платформами онлайн-торговли.

Одним из самых главных плюсов этой трансформации для капиталиста является снижение затрат на оплату труда продавцов, а значит увеличение прибыли. По крайней мере, это прослеживается для крупных ритейлеров и онлайн-платформ.

Меня же интересует можем ли мы взять информацию как некий квантификатор перехода из одного качественного состояния в другое для рассматриваемого явления? Я полагаю - можем. Может быть не сама информация, а скорость ее распространения является основой развития процесса розничной торговли. Но для меня сути это не меняет. Есть изменение явления в результате накопления квантификатора модификации. Это все результаты технического прогресса, скажет мне человек игнорирующий марксизм. Но мы то знаем, что прогресс это и есть развитие и просто нужно внимательно рассмотреть этапы этого процесса. 

Сейчас начнется такое, что, думаю, большинство марксистов начнут кидаться в меня разным. Ибо я собираюсь таким образом из материального мира перейти в мир идей. Возникает извечный вопрос о примате материи или идеального(духа). Попробую оправдаться и закрыть часть обвинений меня в идеализме. На текущем уровне развития науки (! все-таки настаиваю на научном подходе в познании мира) мы не имеем никаких весов или линеек, способных описать скорость распространения информации (идей) или ее трансформации. Мы лишь констатируем факт существования этих явлений, как когда-то люди констатировали движение Солнца. И давайте вспомним о генетическом коде (кто сразу вспомнил Соловьева?). Современная наука говорит, что нет живых клеток не несущих в себе ДНК, т.е. носителя информации(?!). В информатике есть такое понятие как "машинное слово", которое мы можем, в некотором виде, применить и к генетической информации. Исходя из этого мы можем заявить, что сначала было "слово" (слава ----!), а уж потом дело развития живой материи по обра... а... нет... пока без образа. Зато мы можем получить следующий вывод - живая клетка неотделима от информации, заключенной в ней самой. В таком случае может возникнуть вопрос о корректности изречения "пустота - это форма, форма - это пустота"(это из другого религиозно-философского течения мысли).

Для кого-то сразу же ставится под вопрос реальность самого окружающего мира, но как учит нас диалектический материализм, мир - это объективная реальность, данная нам в ощущениях (информации снятой с органов чувств и обработанной мозгом). Предлагаю оставаться в рамках этой парадигмы и просто увеличить значимость информации, как самостоятельного свойства объективного мира, развитие(изменение) которого отражается через действия высокоорганизованной материи на самом окружающем мире. Что бы не делали люди, это результат обработки различной информации. От ощущения холода или голода, до поисков законов мироздания через наблюдение за происходящими явлениями. Чтобы мы ни делали - мы должны принять решение (сознательно/осознанно или не очень), опираясь на входные данные. В третьей главе "Капитала" Маркс  подводит к выводу о том, что стоимость является "объективной идеальностью", отражением материального мира в идеях, общественных идеях. Значимость же информации(идей) и её скорости распространения, как самостоятельных свойств объективного мира, нам показал некий Йозеф, приятель художника, будь они неладны. Такая вот борьба и единство противоположностей получается. 

"Торговля (товарообмен) — это обмен овеществленным трудом, основанный на общественной идее (информации) о стоимостном отношении товаров." Интересно, что скажут граждане Ярский, Попов и Садонин (шутке).
Любопытно, насколько соответствует действительности это допущение?

* Бабки, $#%@ ,бабки!

По Марксу, деньги - это общественные отношения воплощенные в форме вещи. Это товар, ставший всеобщим эквивалентом. Постараемся запомнить. Это действительно важно. А еще важно запомнить, что этот всеобщий эквивалент обладает собственной потребительной стоимостью, т.е. может быть применен не только для расчетов, но и как необходимый материал в производстве. По крайней мере так было во времена Маркса, когда общепринятыми деньгами было золото.

Полностью историю развития денег как платежного средства я рассматривать не буду. Интернеты позволяют самостоятельно познакомиться с этим процессом. Для меня важен только отрезок после Первой мировой войны. Т.е. эпоха империализма (как высшей формы капитализма).

** До Бреттон-вуда.
Все еще действовал "золотой стандарт". Основной резервной валютой, свободно конвертируемой в золото был фунт. Результатом ПМВ и "Великой депрессии" стали изменения в финансовой политике ряда государств, в том числе США и Великобритании. Так мировое сообщество приплыло к Бреттон-вудской конференции, после которой появились МБРР и МВФ, а валюты были связаны твердыми обменными курсами через доллар с золотом.

** Ямайка.
В 1978 завершилась трансформация мировой валютной системы в современный вид с отменой золотого стандарта, золотого паритета и отмена фиксированных курсов валют. С тех пор началась эпоха спекуляции деньгами, т.е. получение прибыли от торговли всеобщим эквивалентом, лишенного привязки к золоту. Т.е. фактически (насколько ошибочно это мое мнение?) деньги потеряли потребительную стоимость. Зеленые бумажки нельзя применить иначе как для обмена на товары/услуги.

** Текущий вид.
С развитием прогресса в целях увеличения капитала, через ускорение товарооборота и увеличение кредитования, все сильнее развивались формы безналичной оплаты. Пластиковые карты также не имеют никакой потребительной стоимости, как и бумажки. А фактическим носителем "стоимости" становится информация находящаяся на серверах банков. Естественно, что появился новый суррогат - криптовалюта.
На мой взгляд, крипту можно рассматривать как аналог первых ассигнаций. И в скором времени мы сможем смело сказать "Всё, Нео, денег нет. Держись."

Бытие переходит в Ничто? Или нет? Или да?

В условиях капиталистического общества это естественно приведет к жесточайшей, терминальной форме фашизма. Даже представить не берусь, на что это будет похоже. Возможно, Ефремов в своем "Часе быка" описал подобное общество очень четко. Ну или фильм "Время" может показать примерный вариант.

На мой убогий взгляд, деньги просто проявляют свою суть - инструмент политической власти. Сейчас - диктатуры буржуазии. Большинство человечества выдало право узкой группе лиц вооружать и снабжать всем необходимым машину подавления, подчинения, уничтожения.

Исследование швейцарского банка UBS сообщает что на планете имеются 2668 миллиардеров. За год 360 человек утратили этот статус, 273 - приобрели. Совокупное состояние долларовых миллиардеров за год сократилось до $12,7 трлн с $13,1 трлн.

0,00003335% от всего человечества являются долларовыми миллиардерами, а значит держат в своих руках всю полноту политической власти. Разумен ли homo sapiens sapiens?

Меня же интересуют вопросы реализации подобного инструмента в рамках общества диктатуры пролетариата. Признаюсь честно, я считаю, что только такая форма правления допустима до последнего этапа построения коммунизма. Любые заявления об "общенародном государстве" - это шаг назад.

Как должна будет организована сеть "криптогосбанка"?
Насколько прозрачной должна быть система "кошельков"? Как у биткоина?
Какие принципы должны быть заложены, чтобы обычный гражданин оставался свободен в использовании заработанного?

* Услуги.

Возьму к рассмотрению самый гротескный вид услуги, получивший хождение в последние годы - "инфоцыганство".
Кто и как устанавливает стоимость часа говорения ртом Тони Роббинса или Саши Митрошиной?
Почему Митрошина (ты когда деньги людям вернешь?) не может установить ценник за свои "курсы" равный ценнику Роббинсона? Потому что Тони - эксперт мирового уровня? Кто определил его в эксперты? По каким критериям? Что значит "мировой уровень"?
Короткий ответ - только чье-то субъективное мнение определяет стоимость услуги. Это не отменяет объективных(материальных) затрат в процессе оказания услуг. Но в корне лежит информация (идея) о том, сколько за предоставлении услуг готовы заплатить (платежеспособный спрос). Потолком стоимости услуги является лишь жадность. Где-нибудь в Улан-Удэ нет возможности стричь людей так же дорого, как в Москве.
И если вернуться к распространению информации, то все знания, которые продают "инфоцыгане" можно получить из литературы. Просто нужно читать чуть больше, чем длится курс "коучинга". А потом еще и заняться самой сложной работой - думать.
Все это также можно применить и к онлайн-образованию в сфере IT. Уровень знаний, сопоставимый с результатом курса за сотни денег, можно получить самостоятельно с помощью книг и youtube, так как желающих вступить в конкурентную борьбу за получение денег из воздуха стало очень много и появились те, кто эту информацию отдает бесплатно, в обмен на монетизацию от гугла. Или же сама корпорация добра. Курс по машинному обучению можно пройти у них даром, если вы нуждаетесь не в дополнительном сертификате, а в знаниях.

* Предпринимательские способности. (выжимка из Э. Роббинса бесплатно)

Для "успешного успеха" любого "бизнеса" в сфере производства (потому как жизнь человеков невозможна без потребления материальных благ, а значит они всегда будут что-то потреблять) нужны следующие факторы:

** дешевые материальные ресурсы
В первую очередь, подразумеваю средства производства. И, желательно, получить эти средства под свой контроль и управление абсолютно бесплатно. Нахалявить, так сказать. Как это, например, произошло в период приватизации активов, созданных трудом нескольких поколений советских граждан. На западе это работает точно также. Уильям Гейтс III не даст соврать. Он был настолько круче Чака Норриса, что начал не просто "с нуля", а с шести нулей. И достались они ему абсолютно бесплатно, просто по факту рождения. (Естественно, я ему завидую. Как иначе?) Если ты не родился с серебряной ложки во рту, то лучше не бросай колледж, а то будешь всю жизнь работать на дядю и никогда не попадешь на страницы "Форбс".

** четкое или не очень представление о чужих потребностях
То, что принято называть "спросом". Пока ты ничего не знаешь о том что, где, сколько, и по какой цене(приблизительно) ты можешь реализовать, то организовывать "свечной заводик" может оказаться делом неблагодарным и абсолютно затратным. И внезапно окажется, что самым главным элементом в законе спроса и предложения будет информация о платежеспособном спросе. Ведь ты же не собираешься дарить произведенные товары? Нет?
Конечно, его можно сформировать с помощью пропаганды(рекламы), но это ресурсозатратная услуга см. выше.
Раньше этот спрос ты мог изучить экспериментальным путем, таскаясь с одного края глобуса на другой с вещами, которые могут оказаться интересными, по твоему мнению, там, куда ты топаешь. И здесь мы снова возвращаемся к вопросу о доступности информации и скорости ее распространения.

** чужой труд по максимально возможной низкой цене (желательно даром)
Банально? Хочется поспорить? Тогда читаем "Капитал" и усердно думаем над тем, что видим в реальной жизни.

** коммерческая тайна и нужные люди.
Самое главное - это эффективно скрыть максимум информации от существующих или потенциальных конкурентов и клиентов. Тот кто действует ради прибыли, а не общего блага всегда должен скрывать или искажать максимум информации. Мелкий шрифт в кредитных договорах, "вред ГМО", эффективность "зеленой" энергетики, отключение Европы от газовой трубы. А еще могут быть нужны люди, которые могут помочь под видом достижения общественной пользы выкачать из госбюджета (общественных денег) какое-то количество ресурсов или избавить от преследования по закону в результате раскрытия(!) информации о нарушениях этих самых законов, или с помощью грубой силы произвести рейдерский захват "чужого" предприятия. Это я так тихонько намекаю на желательность для каждого предпринимателя, жаждущего финансового мегауспеха, срастись, породниться с криминалом и бюрократическим аппаратом государства. Все "лучшие" люди всегда сбиваются в плотный клубок.

А в итоге получается, что суть "предприимчивого предпринимателя" - ложь, халява, гонор.
В социалистическом обществе нужны будут не предприниматели, а "организаторы дела". И разница между этими типами людей заключается во внутренней мотивации. Первые ставят себя над обществом, вторые - не отделяют себя от него.

Все сказанное ранее вполне действует и в случае с оказанием услуг. 

** Экспресс-тест на предпринимательские способности.
Вводная: Ты, мой дорогой юный атлант, являешься владельцем рыболовного флота и имеешь право на вылов в определенном секторе мирового океана. Ихтиологи сообщают, что при сохранении текущего способа ловли через 15 лет в этом, выделенном тебе, секторе не останется рыбы.

Задача: максимизировать прибыль от этой деятельности.


Попробуй подумать самостоятельно, прежде чем прочтешь правильный ответ.

Ответ: Необходимо интенсифицировать лов и сократить срок эксплуатации участка до 10 лет. После чего продать флот на металлолом, а все деньги отправить в другой "бизнес". Например "вложиться" в акции Apple.

Если ты внутренне не готов поступить подобным образом, то, мой дорогой атлант, ты никогда не выживешь в океане предоставленных капитализмом "возможностей". Потому что ты не акула бизнеса, а просто гупешка.

* К вопросу о законе стоимости.

#+begin_quote
Каким бы образом ни устанавливались и ни регулировались первоначально цены различных товаров по отношению друг к другу, движение их подчиняется закону стоимости. Когда уменьшается рабочее время, необходимое для производства товара, падают и цены; когда оно увеличивается, повышаются при прочих равных условиях и цены. 
#+end_quote

#+begin_QUOTE 
Цена, или денежная форма товаров, как и вообще их стоимостная форма, есть нечто, отличное от их чувственно воспринимаемой реальной телесной формы, следовательно, – форма лишь идеальная, существующая лишь в представлении. Стоимость железа, холста, пшеницы и т. д. существует, хотя и невидимо, в самих этих вещах; она выражается в их равенстве с золотом, в их отношении к золоту, в отношении, которое, так сказать, существует лишь в их голове.
#+end_QUOTE

К.Маркс

И суть этой идеи проста, на мой взгляд, - "час жизни человека может быть определен в материальном выражении", а значит чья-то жизнь может стоить дороже, чья-то дешевле, а чья-то вообще ничего. Вот такой вот гуманный гуманизм. Где-то упала слезинка ребенка. Голодного, бездомного ребенка.

В эпоху, когда человечество производит количество продуктов достаточное чтобы накормить всех, мы имеем сотни миллионов голодающих на планете. В странах, где пустуют сотни миллионов квадратных метров жилья существует бездомность. Люди, способные к труду, а значит могущие производить продукты питания, ширпотреб или строить жилье лишены возможности трудиться и честно заслужить свою порцию благополучия лишь по тому, что "нет денег(!) на развитие", что "рынок насыщен" и мы тут все в кризисе перепроизводства.

Чьи-то жизни могут быть спасены, "исправлены" просто при ином способе перераспределения имеющихся ресурсов. Но вместо этого большинство продолжает с упоением разглядывать как мизерная группа лиц "проедает" чье-то время жизни, мечтая любыми способами залезть в эту кучку. Так же лишая тысячи, сотни тысяч и миллионы людей права стать учеными, врачами, получить дозу инсулина, а порой даже просто кусок хлеба.

Точно ли буржуи не людоеды?

* Рассуждения об учете
Что является кирпичом оценки экономической жизни? Статистика.
Откуда она берется? Из результатов хозяйственной деятельности предприятий и домохозяйств.
А как ведется учет хозяйственной деятельности предприятий? С помощью бухгалтерского учета.
В [[https://www.marxists.org/russkij/lenin/works/disaster.htm][своей работе]] Владимир Ильич указал механизмы реального контроля пролетарской власти над всей экономической жизнью страны.
В последствии он это неоднократно повторил:

Ленин В.И. — Очередные задачи советской власти (04.18)
https://youtu.be/DvvKhNyuKDA

Ленин В.И. — Экономика и политика в эпоху диктатуры пролетариата (10.19)
https://youtu.be/rqlFr5j5MpM

Ленин В.И. — О кооперации (01.23)
https://youtu.be/2PwWsFXOK1A

Ленин В.И. — Лучше меньше, да лучше.  (03.23)
https://youtu.be/QgFnBD7Q0kg


Только обеспечив возможность работникам  контролировать хозяйственную деятельность можно говорить об обобществлении предприятия. Без участия каждого сотрудника в сбережении, развитии общего достояния невозможно обеспечить и сохранность политической власти пролетариата.
Без общественного контроля за бухгалтерией предприятий и ведением хозяйства не будет реальной демократической власти. Он, в свою очередь, невозможен без отмены коммерческой тайны. Отмена тайны невозможна без отмены права частной собственности на средства производства. Она невозможна без изменения строя. Упс. Расходимся. Это утопия.

Ни одна финансовая махинация не может обойтись без участия бухгалтера. Ни один "попил" бюджетного бабла не может обойтись без следов в бухгалтерии.
Кто помнит случай с ЕГРН и ответственным государственным чиновником? Точнее с информацией о недвижимости его детей? Помните, чем все закончилось?

Развитие технологий подарило нам возможность дистанционно участвовать в голосовании, платить налоги не выходя из дома. На каждом крупном предприятии работает ERP-система. Так же дистанционно отправляется налоговая отчетность. И вся "цифровизация" госструктур, ведущаяся сейчас может послужить отличным фундаментом общества нового типа.

Вот если бы наши руководители скрестили 1С с блокчейном, чтобы можно было избежать фальсификации "первички", какой прекрасный был бы результат. Мечты, мечты...

Только когда каждый пролетарий будет "добровольным сотрудником ОБХСС" и будет выполнять эту работу на совесть пару раз в месяц, то контроль будет настоящим. На местах все равно будут пытаться крутить и мутить воду. Поэтому нужен так же и дистанционный аудит бухгалтерии на условиях анонимности контролеров и вынесение коллегиального решения о выставлении вопросов к предприятию. Миллионы обученных "кухарок" при помощи нейросетей с доступом к данным могут взять под неусыпный контроль все производство-распределение товаров со снижением уровней коррупции и разворовывания. Маткульт-привет Савватееву!

Раз уж затронул компьютеры, то стоит высказаться по мнению Вассермана о потребностях для планирования. Уже больше десяти лет назад один гражданин на сервере начального уровня (примерно 5 к$) смог выстроить модель для планирования экономики Швеции ("Народная республика Walmart"). Сколько потребуется для рабочей системы планирования экономики России? 50? 80? А если без распилов? Да при точных входных данных? А?
Только одна беда и ее озвучил Сафронов - кто те люди, которым будет доверено планирование и управление ЦОДом? Как контролировать центральный узел? Нейродетекор лжи еще не придуман.
Как обеспечить децентрализацию центрального узла? Противоречие-с... А значит через его разрешение можно найти путь развития. 

А вот всякие маркет-плейсы после проработки могут превратиться в систему социалистической кооперации. Тогда вся мелкотограшеская предпринимательская деятельность начнет отмирать за ненадобностью. 

Если у людей с мещанским сознанием есть шанс сбиться в плотную группу и начать "хорошо жить" за чужой (общественный) счет вне пределов контроля, то так, скорее всего, и произойдет. Только если миллионы глаз со всей страны будут заглядывать в карман депутатов, директоров и т.п. можно будет говорить о каких-либо реальных механизма контроля экономической, а значит и политической жизни. Это должно быть не тайное наблюдение, а обыденное правило общежития. Ты назначен ответственным, будь добр играть по установленным правилам. Шведы и финны стараются подобное сделать. И это, наверное, самый лучший вариант. Только осознавая, что расхищение ведется из личного кармана каждого трудящегося, он, этот трудящийся, будет бежать к ближайшему компу в попытке найти эту "крысу". Лозунги и идеи плохо работают, если нет инструмента для их подтверждения в повседневной жизни. Только так это войдет в привычку, в культуру общественного бытия, которое сформирует общественное сознание.

Как это можно реализовать?
Кому доверить?
Кто будет контролировать технических сотрудников?
Кто, черт побери, те гении, что решат вопросы програмно-аппаратной реализации?

* Технологии.

Технологии неизбежно приводят ужесточению контроля над населением. АНБ со мной согласится. Как вы считаете, товарищ майор?

Что с этим можно сделать в демократическом обществе? Полностью отказаться? Вряд ли в этом есть смысл. Психологи доказали, что людям легче вести себя в рамках приличий, если они знают, что за ними кто-то наблюдает. Парадокс психики. Так можно ли это использовать на благо? Если уж социализм - это монополия развернутая на благо общества, то возможно ли развернуть тотальный контроль на благо общества и под контролем самого общества? Например ввести обязательный контроль над ЛПРами государства? С одной стороны есть риски личной безопасности. Противоречие-с... А значит снятие этого противоречия даст новый виток развития.

Как находить людей живущих "все для всех и ничего себе" (как поет один блогер), чтобы поручать им самые важные направления?


* Государство?
  
При текущем уровне социального развития отсутствие государства, как инструмента подавления попросту невозможно. Потому как до полного коммунизма риски реставрации будут сохраняться. Как изнутри, так и извне. Пока будут существовать буржуазные национальные государства борьба за реставрацию будет продолжаться. И аппарат должен будет существовать, только с каким уровнем сокрытия информации и гостайны? Честность в политике - результат силы. Привычка к подковерности снова приведет к разложению руководящей группы. Только мировая революция, в ходе которой большая часть глобуса станет социалистической, может привести к началу упразднения государства.
  
Основная проблема - механизм общественного контроля политической власти. Если в буржуазном обществе мы можем спокойно принимать за истину тот факт, что власть предержащие лгут общественности, то при социализме (переходном этапе к коммунизму, где сохраняется буржуазное государство, пережиток прошлого) каждый гражданин должен по умолчанию считать, что правительство лжет. Лучше ошибиться и признать честность "оппонента" - правительства, чем допустить деградацию общественной формации. Одна большая трудность - гражданин должен хорошо разбираться в политической жизни уже к совершеннолетию.

Какие принципы должны преобладать в обществе, чтобы политическая власть не была результатом подавления, а стала результатом осознанного выбора миллионов людей?

* Малолетний либерал - личинка коммуниста?

Если мы уж заговорили об идеях, то я затрону и носителей отдельных идей.

Уже в кратчайшие сроки мировая экономика, и ее результат - политика национальных государств, поставит каждого человека, вовлеченного в общественные отношения, а, тем или иным образом, это каждый человек на планете, перед жестким выбором стороны в игре под названием жизнь. Не будет "хаты с краю". Или "обмани ближнего, нагадь на нижнего", или "человек человеку друг, товарищ и брат". "Мы все равны" или есть "носители голубой крови, люди с хорошими лицами" - это единственная дилемма, стоящая перед человечеством всю его историю, которая все сильнее выходит на первый план. Это, по сути своей, сознательный выбор комплекса идей, который большинство делает неосознанно, подчиняясь культурным рамкам общества в котором живет.

Носитель либеральных идей, идей буржуазной демократии, борец за все хорошее и против всего плохого, тщательно считающий слезинки детей, пытается устоять на тонюсенькой линии этого водораздела, не смея сделать еще один маленький шаг вперед, в прогресс, как личный, так и общественный, прикрывая свою, фактически звериную, натуру фиговым листком красивых фраз о моральности, основанных на некомпетентности в вопросах экономики, истории и философии, да эмоциональными оценками "нравится/не нравится".
Мещанскому сознанию гораздо проще сделать шаг назад, в угар фашизма, спокойно списывая чужое право на жизнь привычным, усвоенным, нежно воспитываемым социал-дарвинизмом. Либералу никогда не хватит смелости и честности признаться самому себе в своем яростном желании выжить за счет поедания себе подобного. Этакий рафинированный гурман, наслаждающийся собственным великолепием, предпочитающий к печени употребить бутылочку кьянти. Для объяснения своей позиции он будет подтягивать любые метафизические идеи о невозможности изменить суть общественных отношений. Будь это божественный промысел или карма, все что угодно, лишь бы не подойти к вопросу с точки зрения науки. С позиций диалектического материализма. Ведь для этого нужно разобраться в вещах, которые реально влияют на его жизнь, а не прятаться за идеалистическим объяснением мира.

Достаточно сохранить классовое разделение, сегрегацию по толщине кошелька на патрициев и плебс, и все эти его "свобода", "равенство" превращаются в химеру. Будь уже до конца честен перед собой - при капитализме равенство возможностей невозможно в принципе. Ну или создай российский "Майкрософт" или "Эппл". Капитализм же дарит возможности! И пока существует это разделение на лучших/худших всегда найдутся те, кто хуже и в других национальных государствах. Те, чей дом ты имеешь право отжать. Те, кто не имеет права обменять свой труд, свой хлеб, по условиям лучшим, чем ты навяжешь силой или обманом, называемым красивым словом "маркетинг".

Достаточно сделать шажок вперед и устранить классы, для начала хотя бы в своей голове. Идея бесклассового общества - это идея мира, в котором правит социалистическая(пролетарская) демократия (хочется сказать "народная демократия", но это масло масляное). Где от рождения все равны в возможностях на реализацию личностного потенциала, в праве на достойное обеспечение себя честным трудом (физическим или интеллектуальным не важно, с развитием технологий физический труд будет автоматизироваться по максимуму). Где действует законность. Где никто не боится остаться без куска хлеба на улице потому, что ипотека или какие еще причины. Не только лишь ты один такая уникальная снежинка, заслуживающая право оставить после себя след, достойный Человека.

Для разрыва шаблона процитирую тирана:

#+begin_quote
Было бы неправильно думать, что можно добиться такого серьёзного культурного роста членов общества без серьёзных изменений в нынешнем положении труда. Для этого нужно прежде всего сократить рабочий день по
крайней мере до 6, а потом и до 5 часов. Это необходимо для того, чтобы члены общества получили достаточно свободного времени, необходимого для получения всестороннего образования. Для этого нужно, далее, ввести общеобязательное политехническое обучение, необходимое для того, чтобы члены общества имели возможность свободно выбирать профессию и не быть прикованными на всю жизнь к одной какой-либо профессии. Для этого нужно, дальше, коренным образом улучшить жилищные условия и поднять реальную зарплату рабочих и служащих минимум вдвое, если не больше, как путём прямого повышения денежной зарплаты, так и, особенно, путём дальнейшего систематического снижения цен на предметы массового потребления.
#+end_quote
И.В. Сталин

Один мой либеральный приятель сказал: "Ваш "совок" развалился, а вы снова хотите затащить нас в безумные эксперименты"!

Про развал я отдельно выскажусь, а пока возьмемся за эксперименты. Вся история человечества - это один большой эксперимент по выживанию вида в меняющихся условиях. То, что ты сегодня принимаешь как данность, скорее всего, когда-то не существовало. Интернет, мобильный телефон, автомобиль и теплый сортир, антибиотики и книги. Ты скажешь - это все результат прогресса, которого не может быть без экономического интереса. А я отвечу - Линус Торвальдс, Альберт Эйнштейн и сотни тысяч живших и живущих людей, которым важнее заниматься тем, что им интересно. Тех, кого не интересует "булшит джоб", закрывающая потребность в деньгах на текущий месяц, потому что заглядывать в будущее на больший срок страшно из-за пугающей пустоты прожитой так жизни. Ты хочешь прожить батарейкой, на которой работает этот механизм самообмана или ты хочешь быть свободным и управлять тем, что непосредственно влияет на твою жизнь? В любом случае, как бы сейчас не развернулись события, "просто жить" не получится ни у кого. Вполне вероятно, что очень скоро наступит момент, когда экономика хорошенько рухнет. Скорее всего, на всей планете. И будет великое счастье, если глобус останется цел. 

Могу ошибаться, но если либерал хотя бы на один день прекратит врать самому себе о том, как устроен мир, то он станет марксистом.

В качестве примера я, пожалуй, приведу нескольких видео-блогеров-борцунов с несправедливостью. Мне понравилась борьба "просрочкой" в магазинах Москвы. Невообразимо умилительно смотреть на борьбу с последствиями капиталистической логики. С естественными последствиями необходимости увеличивать капитал. Внезапно?
Или борьба с коррупцией, в мире, где "всё просто так, кроме денег". Вы серьезно рассчитываете на результаты?
А интереснейшие теории о "win-win" психологии при капитализме?

Вы так яростно стремитесь к "открытому обществу", что не замечаете того, что никто так не хочет открытого общества, как коммунисты. Открытого и прозрачного как слеза младенца. Только так и можно построить демократию.

Я часто спрашивал своего приятеля, что же есть для него "свобода", которой он лишится, если вдруг наступит коммунизм. Ни разу я не получил внятного ответа. Что за "свобода" требует защиты рабства?

Радует только одно - нет никакого либерала. Я имею в виду, что нет никакого цельнолитого метафизического "сознания" или "характера", однажды оформленного и неизменного "Я". Личность любого человека - сложный результат физиологических особенностей и опыта, обработанного тем или иным способом мозгом. В результате получения нового опыта человек может измениться, порой радикально. Это можно легко доказать за пять минут. Для этого не надо работать в шахте по двенадцать часов на протяжении нескольких лет. Только пять минут мысленного эксперимента. Тебе понравится, мой дорогой любитель всего хорошего. Поставь таймер на телефоне.

Садимся прямо, спина вертикальная, голову не задираем. Ноги на полу. Руки - как удобно. Нигде ничего не перекрещиваем. Пять-семь глубоких вдохов. И начинаем.
Ты взлетаешь над Землей, в стратосферу или выше. Как тебе удобно. Достаточно видеть вращающийся сине-голубой шарик.
И начинай желать каждому человеку на планете достойную работу, дом, свободное время, чтобы читать и общаться с друзьями и семьей. Каждому ребенку - все необходимое: еду, воду, кров над головой, игрушки, книжки, школу, лекарства. У всех есть все, что позволяет жить счастливо и свободно. Радикальные террористы убирают оружие и идут строить дома, заводы, пахать пашни и убирать урожай. Не важны ни цвет кожи, ни страна происхождения, ни религиозные предпочтения. От тебя к каждому человеку отправляется белый лучик. Их становится больше. На поверхности планеты загораются белые точки. В Африке, на Дальнем Востоке, в Южной и Северной Америке, Европе и Азии, Австралии и Новой Зеландии. На каждом островке, где живут люди. Точек становится все больше и больше, пока вся Земля не начинает светится ярким белым светом отправляя белые лучи в космос. У всех есть причина для счастья.
Можно прикрыть глаза и смотреть на эту красоту пока не запищит таймер. Дыхание ровное и спокойное. 

Получилось? В любом случае - не повторяй этого больше никогда, а то еще чего добро захочешь изменить этот мир. Я тебе запрещаю. А если ты спросишь - а как же я? А ты тоже - тот самый "каждый человек". Не жадничай хотя бы внутри своей головы.

И в контексте предыдущих моих домыслов - этот эксперимент есть обработка сознательно сгенерированной  высокоорганизованной материей информации с целью формирования нового опыта, способного повлиять на работу этой самой высокоорганизованной материи. Возможно, даже немного изменить уровни нейромедиаторов в крови. Таких как окситоцин и дофамин (требуется научное подтверждение).

* Крах социализма в СССР.

Почему-то правые или либералы в любом споре начинают с того, что на всех уровнях страной управляли настоящие коммунисты весь период. Ха-ха три раза.
Достаточно выяснить классовые корни [[https://youtu.be/UrHzaSGIVeA][светоча]] или отца русской демократии Бориса-Храни-Господи-Америку.
Заявлять что вся масса народа недавно научившаяся читать внезапно стала марксистами-ленинцами с хорошим пониманием основ, примерно тоже, что заявить что каждый гражданин Украины с 1991 года стал сторонником праворадикальных идей и чествует Бандеру. Не бьется с фактами. Политические воззрения в массах были, есть и будут еще долго очень разными.
И все же при Сталине хотя бы учебник простой выпустили ("Политграмота", 1935). А вот то, что началось после его смерти вызывает кучу вопросов, которые пока невозможно разрешить - часть значимых архивов все еще закрыты, насколько я слышал от тов. Спицына.
Раз уж взялся за диамат, то нужно продолжать. Крах экономики, говорили они, разваливая страну по национальным государствам. Что ж. Согласен, раз вся политика есть отражение экономики, то у всех политических решений должны были быть экономические корни или как минимум желание эти корни создать (волюнтаризм тоже необходимо учитывать).
Прочитав некоторое количество трудов В.И. Ленина и И.В. Сталина можно придти к выводу об одной линии партии, изменившейся в результате угроз извне. Потом война. Восстановление и модернизация индустрии. Той самой сферы экономической деятельности, которая является хребтом экономики и приводным ремнем прогресса. 

Итак, Сталин умер и XX съезд. Можно однозначно говорить о не особой честности Никиты Сергеевича в этом выступлении и мемуарах. Причин доверять в дальнейшим его высказываниям и поступкам не вижу. Потом начались экономические реформы по-большей части волюнтаристского характера. [[https://youtu.be/t7lVlsav1XY][Совнархозная реформа]] и повторный пересбор планового аппарата наверняка позволил некоторым лицам на местах получить финансовую выгоду. В любой конторе, где допускается принцип "день за белых, день за красных" всегда найдутся люди способные успешно реализовать возможности по личному обогащению. Все это потом мы сможем наблюдать в комедиях Гайдая. Значит эти явления мало того что встречались в жизни, но и не вызывали жесткого отторжения. О потворстве воровству [[https://youtu.be/VQHZgpByfos][Сталин говорил]] (35:00) еще в 1926 году. В народные массы коммунистические идеи заходили не так быстро, как этого хотелось бы Ленину или Сталину, по мере воспитания нового поколения людьми, видевшими положительные изменения в их жизни. А когда поломали систему пропаганды в 60-х, превращая марксизм в катехизис, то рассчитывать на рост сознательности стало просто нелепо. Плюс первые зерна "потребительства" в советском обществе положила та самая программа 1961 г которую мало кто понимал с точки зрения роста потребностей всего общества. Да и сам XX съезд вычеркнул все сталинские теоретические наработки. О росте напряженности классовой борьбы по мере развития социализма. Ну и отмена диктатуры пролетариата, само собой. Уж не знаю сколько преподавателей продолжили пользоваться учебником Селиванова "Воспитание воли школьника" щедро сдобренного восхвалениями Иосифа Виссарионовича, но все же имевшего в себе толковые мысли.

Все эти решения XX съезда и последовавшие за ними изменениями в идеологическом плане мне хочется сравнить с тем, как человек, решивший вести здоровый образ жизни и на некоторое время отказавшийся от табака и алкоголя, допускает мысль, что от двух затяжек после пива в пятницу ничего страшного не будет.

И таким образом люди, которые объективно начали в материальном плане жить лучше, чем раньше начали гонку по превращению в мещан. Жилье, дачи, автомобили, сервизы и все остальное стало понемногу перевешивать стремление к коммунизму, который обещали к 80-му году. Совсем рядом. Хотя за такое обещание всех идеологов и руководство необходимо было смещать. Но коммунисты это "схавали". Члены партии все чаще превращались, а иногда в этом не было необходимости, в "партбилетоносцев" не понимающих ничего в теории и не читавших даже базовых работ. В добавок ко всему разрасталась спекуляция, приписки, появлялись "цеховики" и со всем этим большинство граждан просто смирились. Да еще появились всякие телевизоры, которые положили начало разобщению людей.

Как сказал один видный историк "Если люди начинают мериться хрусталем, то они не будут объединяться".

В 1980 году моя бабушка, работница совхоза, дочери своей сказала "от чего ушли к тому пришли". Т.е. человек имеющий мало-мало политической грамотности со времен воспитания в эпоху Сталина четко видела процессы загнивания на месте. У меня в семье в виде хохмы ходит случай когда представителей народного контроля на базе ОРСа подкупали возможностью выкупить коробку майонеза в 90м году. Еще в 1984 году, при смене директора завода ходили слухи, что не только он уезжает на новую должность, но с ним уехал состав строевого леса из запасов предприятия.

В-общем и целом - наши минусы проистекают из наших плюсов. Общество стало жить в целом значительно лучше, стремление бороться за изживание пережитков капиталистических нравов, мещанства стало меньше. Сила воли в тепле и уюте размягчается. "Запой" капитализма был предсказуем.

То, что многие считают "демократизацией" послесталинского периода, я бы назвал откат в буржуазный либерализм. Как рабочий класс сам не может подняться в борьбе выше трэдюнионизма, так и мещанин в своей политической позиции не может подняться выше слегка розового соц-дема в лучшем случае. А то и стать яростным либералом. Это движение наименьшего сопротивления. Не нужны знания, не нужны воля и дисциплина.

Если бы можно было на том этапе развития устранить/изменить следующие факторы, то, возможно, никаких перестроек бы не было.

1. Технологии обеспечения широкого вовлечения в контроль хозяйственной деятельности широких масс.
2. Фактор "завмаг/завсклад/уважаемые люди" - разворовывание на уровне ответработников.
3. Снижение эффективности народного контроля (изначально рабкрина).
4. Отстранение и самоотстранение коллективов от контроля (фильм "Премия").
5. Был и размеренный, планомерный саботаж. И антисоветская агитация (имеется личный опыт 90-91 годов).



* Зачем жить при коммунизме?

Если коммунизм - это закрытие всех насущных материальных потребностей каждого члена общества, то сразу вспоминается анекдот:

Негр под пальмой на родине лежит млеет. Мимо проходит бизнесмен из Европы.
 - Вот ты негр, лежишь бездельничаешь, а мог бы на пальму залезть, нарвать бананов. Пойти на рынок и продать.
 - А зачем?
 - Ну как зачем! На деньги с проданного, купишь тележку и нарвешь на много больше!
 - А зачем?
 - Да ты с проданного уже сможешь купить грузовик и возить большие обьемы, потом наймешь работников, а сам будешь лежать и ничего не делать!
 - А я в принциппе и так лежу и ни чего не делаю!

Коммунист-мещанин - это спортсмен, который каждую субботу "съедает" бутылку водки. Рано или поздно, но ЗОЖ уйдет в сторону и останется только разрушенный алкоголик.

Как избежать омещанивания масс и, как результат, деградации общества?
Чему такому нужно учить людей, чтобы они свободно выбирали свободу творить, мыслить, созидать?
Чем будут заниматься люди, если необходимый труд будет сокращен до 5, 4, 3 часов?

#+begin_QUOTE 
Мещанин — существо, ограниченное тесным кругом издавна выработанных навыков мысли и, в границах этого круга, мыслящее автоматически.

...

А в общем этот лучший гражданин «культурного» мира совершенно похож на того дикаря, который, будучи спрошен миссионером: «Чего ты хочешь?» — ответил: «Очень мало работать, очень мало думать, очень много кушать». Мещанин — это патологический случай, когда крепко усвоенная человеком техника мышления прекращает рост его мысли. 

#+end_QUOTE
М.Горький

Я вовсе не ратую за общество беззаветного аскетизма. Людям требуются и положительные эмоции и комфорт. Мне хотелось бы понять, что может послужить инструментом саморегуляции, самовоспитания, самодисциплинирования в потреблении материальных благ. Особенно когда деньги станут не нужны или исчезнут.

Насколько широкими должны сети культурного, образовательного, научно-технического досуга для взрослых?
Почему люди, у которых будут возможности обзавестись любым барахлом, будут выбирать не "всё что нажито непосильным трудом", а "все что нужно то и есть, а что есть - то и нужно", нередко переходящее во "все для всех и ничего себе"?
Кто будет создавать такую культуру?
Как её можно сформировать?

* Мировая революция и место России в ней.

Мы живем в эпоху пролетарских революций. И, как известно, Россия исчерпала лимит на революции в XX веке. Конечно, очень хочется провести параллели с историей Франции и с 1848-м годом. Действия текущего правительства неизбежно приведут к подъему уровня недовольства. Это понятно, но пойдет ли народ вперед или угрюмо сделает второй шаг назад, в реставрацию монархии, прочно закрепив на себе ярмо наемного рабства или даже превратившись в холопов?

В современных условиях действительно революционная партия будет немедленно задавлена репрессивным аппаратом правящего класса. Возможно, при активной идейной поддержке всех существующих национал-коммунистических ("левопатриотических") сил. Любые попытки устроить "работающее двоевластие" в виде Советов прямо сейчас будет всячески подавляться или возглавляться оппортунистами.

Возможно я через чур жестко оцениваю Геннадия Андреевича и КПРФ в целом, может быть он настолько ленинец, что все эти годы всячески демонстрирует несостоятельность буржуазного парламентаризма и неспособность социалистических партий в таких условиях проводить активную самостоятельную политику. Все может быть. Возможно уже сейчас КПРФ по законам развития начнет агитировать солдат, рабочих, работников села за возврат на рельсы социализма? Или это будет новый социализм в обнимку с капиталистами? Каписоцизм - мир где волки сыты и овцы целы.

Любой, кто отрицает необходимость передачи рычагов управления производством непосредственно рабочим коллективам через обобществление средств производства под единым правительственным контролем действует против интересов трудящегося большинства. Любой, кто ведет речь о возможности сохранить народонаселение и уникальную культуру без скорейшего перехода к социализму выступает против интересов трудящегося большинства. Любой, кто разжигает шовинизм и межнациональную ненависть выступает против интересов трудящегося большинства. Любой, кто пропагандирует защиту Отечества в едином порыве с эффективными управленцами выступает за фашизм. Ничего не меняется сотню лет - социализм или варварство фашизма, как терминальной стадии капитализма.

Никакой реформистский путь не может вернуть Россию на путь развития. Попытки строить "сильную Россию" при сохранении капитализма наталкивались и будут неизбежно наталкиваться на "шкурные" интересы людей владеющих средствами производства. На вывод результатов чужого труда, чужой жизни в финансовую спекуляцию за пределами родной страны, на превращение этих результатов в бессмысленные для миллионов трудящихся виллы, яхты, частные самолеты. В попытке сохранить "тысячелетнюю государственность" эти прекрасные люди, измазавшие наш дом чем-то коричневым, приведут к дезинтеграции страны в попытке решить вопросы их личной выгоды. Попытка сохранить капитализм в России неизбежно приведет к развалу страны, зажатой в тиски санкций и управляемой "эффективными менеджерами" в подобных условиях. Штауфенберги вылезут и сделают все необходимое для сохранения собственной жизни. Своего уровня жизни. Даже сейчас им неважны ни народ, ни "тысячелетняя государственность", которыми они так яростно прикрываются.

Нет, я бы конечно хотел посмотреть, как Зюгановы и Платошкины заберут власть и покажут всю несостоятельность "новых социализмов с человеческими лицами". Где товарность будут преодолевать через сохранение, расширение обособления отдельных производителей (мелкий бизнес). Вот только нет большевиков, которые бы могли подталкивать действиями масс их к этому. Их нет. И скорее всего не будет. Нет людей со стальной волей, с железной дисциплиной. Условия сейчас другие - мы все дети уютных квартир с теплыми сортирами, которые страшно потерять. Это, возможно, именно та часть объективной реальности которая в наибольшей мере влияет на формирование сознания и его составной части - воли.

В 17м были миллионы людей, испытавших на себе лишения войны. Людей и без того не привыкших к высокому уровню комфорта. Людей привыкших к тяжелому физическому труду в любых условиях, которым выдали винтовки. Оставалось только дать людям немного знаний, понимания и указать направления действия. И массы проявили свою волю.

Сейчас никто не будет спорить с тем, что мещанские тенденции, "моя хата с краю", превосходят любые потуги вовлечь массы трудящихся в борьбу за свои права. Возможно, сейчас у себя мы видим отражение ситуации 1918 в Европе, когда провалились революции в Германии и Венгрии. Если это допущение верно, то приходится ожидать подъем революционных настроений не в России и не в Европе. А значит вероятность победы еще одной социалистической революции крайне низка и у человечества практически не остается шансов миновать победы фашизма на всей планете.

В любом случае, на мой взгляд, рассчитывать что в России произойдет мощный подъем классового сознания, даже на дистанции в три-пять лет, которые будут, наверняка, очень тяжелыми для всех трудящихся, более чем утопично. Настолько невероятно, что даже взрывной рост социалистических, коммунистических идей в/на Украине выглядит более реальным.

В лучшем случае, Россия будет опять догонять уже социалистический мир.

* и что же воля?
Ага, личная характеристика. Это не научно. Это не по-марксистки. Это субъективный идеализм.
А вот фигушки, граждане догматинцы.

А вот как цитирует Ленина тов. Корнфорт
#+begin_QUOTE 
Человек сам по себе часть природы, и «…и необходимость природы есть первичное, а воля и сознание человека — вторичное. Последние должны, неизбежно и необходимо должны, приспособляться к первой»
#+end_QUOTE

#+begin_QUOTE 
Воля, как и все сознание человека, является функцией мозга, продуктом его сложной работы.
#+end_QUOTE
В.И. Селиванов Воспитание воли школьника.

Вот так уот. Идеальное свойство личности полностью торчит из физиологии и ее использования. Как работает мозг, так и проявляет себя воля. И это свойство может в некоторых пределах быть тренирована даже взрослым человеком. За деталями я отправлю вас к книжке К.Макгонигал "Сила воли".

А если коротко - наш современный образ жизни сам по себе способен серьезно подрывать это свойство личности. Особенно хорошо это делают разного рода развлечения. Например, игры. Компьютерные игры. Дофамин и все остальное. Лучше, конечно, прочесть эту книжку - не хочу ее пересказывать.

Размышляя над этим свойством людей я регулярно вспоминал то, что прочел о событиях 2 февраля 1945 в концлагере Маутхаузен. Эти события известны как "[[https://ru.wikipedia.org/wiki/%D0%9C%D1%8E%D0%BB%D1%8C%D1%84%D0%B8%D1%80%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B0%D1%8F_%D0%BE%D1%85%D0%BE%D1%82%D0%B0_%D0%BD%D0%B0_%D0%B7%D0%B0%D0%B9%D1%86%D0%B5%D0%B2][Мюльфиртельская охота на зайцев]]". В ночь с 1 на 2 февраля около 500 советских офицеров, часть из которых были коммунистами, совершили побег вооружившись лишь палками, камнями, да барачными огнетушителями. А когда их ловили местные обыватели, мещане, то  забивали разным подручным инструментом, чтобы не тратить патроны, необходимые фронту. Может среди инструмента и молотки встречались.

Этот побег для меня, человека без воли, стал эталоном запредельных мужества и воли, какие только могли проявить люди. Советские люди были действительно сильно другими. Титанически другие.

В общем, решил себе создать традицию - в первую субботу февраля проковылять пешком восемь-десять километров чтобы положить пару гвоздик на ближайший мемориал советским воинам Великой Отечественной. И пешком пойду намеренно - чтобы хоть раз в году подумать над вопросом: "Чем так отличись их быт, опыт, что они смогли выработать в себе такие качества и могу ли я это повторить?"

* Вопросы к обдумыванию.

** Как может выглядеть политическое устройство демократического общества равных возможностей?
Кто будет диктовать волю обществу по решению основных вопросов развития?
Кто больше всего заинтересован в открытости и честности политического руководства?
Почему существование денег (платежного средства) не сможет влиять на судебные решения?
Каким образом ограничивать лжецов или заблуждающихся в способах пропаганды своих идей?

** Каким образом накинуть "намордник" общественного контроля на региональных представителей органов власти?
Может ли им быть собственный Ютуб?
Если нужен, как его контролировать?
Кто его будет делать?
Как принуждать чиновников к финансовому контролю со стороны общественности?

** Что нужно сделать чтобы произошел переход в сознании большей части людей?
Какими словами необходимо пересказать ленинскую работу "Грозящая катастрофа и как с ней бороться", так чтобы она стала еще проще, еще понятнее каждому?
Как показывать большинству критерии оценки политических, социальных, религиозных заявлений?

* Финал

Может быть стоит довести до апофеоза ленинский тезис о размежевании до объединения? Возвести его в куб и отказаться от поиска единомышленников ненадолго? Стать атомом осознанно, сознательно? Сесть на задницу и подумать над огромным пластом вопросов? Взять месяц отпуска от ютубов, срачей в чатиках, пустых развлечений и ударить молотом размышления по собственным идеям?

А потом как начать обмениваться мыслями. Возможно, сначала стоит делать это анонимно, пользуясь всеми способами обеспечения своей безопасности. Но без спора, который приведет к выработке идей, планов действий обойтись будет невозможно.

Если хотя бы в части затронутых тем вы находите зерна логики, то я прошу вас - обдумайте их самостоятельно. Думайте, братья!
Астрологи объявили месяц активного размышления.
Крамола в массах увеличена вдвое.


#Сapitalismus delenda est
🄯 цопылефт
